### ISSUE TITLE
Swift issues

### ISSUE THREAD

**Issue by aperritano** [mobile-web-messaging/MQTTKit#14]
Hi, I'm trying to use the library in a swift project via cocoa pods. I created a bridging header and added "#import <MQTTKit.h>". It fails to build giving messages like these:

../Pods/Headers/MQTTKit/MQTTKit.h:10: unknown type name 'NSUInteger'
..Pods/Headers/MQTTKit/MQTTKit.h:27: cannot find interface declaration for 'NSObject', superclass of 'MQTTMessage'
...
I'm using other cocoa pods libs+swift in other projects and its fine. 

can someone confirm? Any ideas for a work around?

thanks

**Comment by cbwilliamsnh** [comment]
have you figured out how to create the message handler in Swift yet?
